[Autologin]
Relogin=false
Session=
User=

[General]
Numlock=on
HaltCommand=/usr/bin/dinitctl poweroff
RebootCommand=/usr/bin/dinitctl reboot

[Theme]
Current=pixie

[Users]
MaximumUid=60513
MinimumUid=1000
