[General]
showlogo=hidden
logo=/usr/share/sddm/themes/AntergosDark-Layan/default-logo.svg
type=image
color=#1d99f3
fontSize=10
background=/usr/share/backgrounds/antergos/antergos-wallpaper.png
needsFullUserModel=false
