[LightDM]
logind-check-graphical=true
log-directory=/var/log/lightdm
run-directory=/run/lightdm

[Seat:*]
greeter-session=lightdm-slick-greeter
user-session=default
session-wrapper=/etc/lightdm/Xsession
