# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Run dracut(8) for the installed kernel
---
# Specify the output initramfs filename (default: initramfs-<kernel-version>.img)
initramfsName: /boot/initramfs-linux.img

# Optional arguments to dracut; -f is always implied
options: [ "-f" ]
