# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
mode: required
method: legacy
labels:
    step: "Packages"
items:
    - id: ""
      name: "No Desktop"
      description: "Please pick a desktop environment from the list."
      screenshot: ":/images/no-selection.png"
    - id: kde
      packages: [ kde-frameworks, kde-plasma, kde-gear ]
      name: Plasma Desktop
      description: "KDE Plasma Desktop, simple by default."
      screenshot: ":/images/kde.png"
    - id: calamares
      appdata: ../io.calamares.calamares.appdata.xml
      screenshot: ":/images/calamares.png"
    - id: kate
      appstream: org.kde.kwrite.desktop
