---
modules-search: [ /usr/lib/calamares/modules, /etc/calamares/modules ]

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - dracutlukscfg
  - dracut
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-openrc
  - grubcfg
  - bootloader
  - packages
  - removeuser
  - umount
- show:
  - finished

branding: antergos-next

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
